[tools]
chezmoi = "2.70.0"
claude-code = "2.1.81"
codex = "0.116.0"
gemini-cli = "0.34.0"
gh = "2.88.1"
hk = "1.38.0"
just = "1.47.1"
node = "25.8.1"
pkl = "0.30.2"
pixi = "0.66.0"
uv = "0.10.12"
watchexec = "2.5.0"
